UI/SMS.AdminUI/Controllers/BaseController.cs
using BLL.Repositories;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Data.ResponseModel;
using DevExtreme.AspNet.Mvc;
using Newtonsoft.Json;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

namespace AdminUI.Controllers
{
    public class BaseController : Controller
    {
        [HttpPost]
        public ActionResult SetLanguage(string lang)
        {
            if (lang != null)
            {
                Session["Lang"] = lang;
            }

            return Json(new ViewResponse());
        }

        protected override bool DisableAsyncSupport => true;

        protected override void ExecuteCore()
        {
            SetLocalization();
            base.ExecuteCore();
        }

        public void SetLocalization()
        {
            var cultureInfo = new CultureInfo("az-Latn-AZ");
            if (HttpContext.Session["Lang"] != null)
            {
                switch (Session["Lang"].ToString())
                {
                    case "en-US":
                        cultureInfo = new CultureInfo("en-US");
                        break;
                    case "az-Latn-AZ":
                        cultureInfo = new CultureInfo("az-Latn-AZ");
                        break;
                    case "ru-RU":
                        cultureInfo = new CultureInfo("ru-RU");
                        break;
                }
            }
            else
            {
                Session["Lang"] = "az-Latn-AZ";
            }

            Thread.CurrentThread.CurrentCulture = cultureInfo;
            Thread.CurrentThread.CurrentUICulture = cultureInfo;
        }


        public ActionResult GetTable<T>(IQueryable<T> data, DataSourceLoadOptions loadOptions)
        {
            var loadResult = DataSourceLoader.Load<T>(data, loadOptions);
            var serializeData = GetSerializeObject(loadResult);
            return Content(serializeData, "application/json");
        }

        static string GetSerializeObject(LoadResult loadResult)
        {
            var jsonSerializerSetting = new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };
            return JsonConvert.SerializeObject(loadResult, jsonSerializerSetting);
        }
    }
}

UI/SMS.AdminUI/Views/Shared/Partials/_FooterPartial.cshtml
<!-- Footer -->
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy; 2015 - 2018. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
        </span>

        <ul class="navbar-nav ml-lg-auto">
            <li class="nav-item"><a href="https://kopyov.ticksy.com/" class="navbar-nav-link" target="_blank"><i class="icon-lifebuoy mr-2"></i> Support</a></li>
        </ul>
    </div>
</div>
<!-- /footer -->

UI/SMS.AdminUI/Views/Shared/Partials/_HeaderPartial.cshtml
	<!-- Main navbar -->
<div class="navbar navbar-expand-md navbar-dark bg-indigo navbar-static">
    <div class="navbar-brand">
        <a href="index.html" class="d-inline-block">
            <img src="~/images/logo_light.png" alt="">
        </a>
    </div>
    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>
        <span class="navbar-text ml-md-3">
            <span class="badge badge-mark border-orange-300 mr-2"></span>
            Morning, Victoria!
        </span>
        <ul class="navbar-nav ml-md-auto">
           
            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle legitRipple" data-toggle="dropdown" aria-expanded="false">
                    <img id="enLang" src="../../images/lang/az.png" class="img-flag mr-2" alt="">
                    Azərbaycan
                </a>

                <div class="dropdown-menu">
                    <a onclick="ChangeLang('az-Latn-AZ', '@Url.Action("SetLanguage", "Base")')" class="dropdown-item russian"><img src="../../images/lang/az.png" class="img-flag" alt=""> Azərbaycan</a>
                    <a onclick="ChangeLang('en-US', '@Url.Action("SetLanguage", "Base")')" class="dropdown-item english"><img src="../../images/lang/ua.png" class="img-flag" alt=""> English</a>
                    <a onclick="ChangeLang('ru-RU', '@Url.Action("SetLanguage", "Base")')" class="dropdown-item russian"><img src="../../images/lang/ru.png" class="img-flag" alt=""> Русский</a>

                </div>
            </li>

            <li class="nav-item">
                <a href="#" class="navbar-nav-link">
                    <i class="icon-switch2"></i>
                    <span class="d-md-none ml-2">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- /main navbar -->

UI/SMS.AdminUI/Views/Shared/Partials/_PageHeaderPartial.cshtml
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Dashboard</h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-bars-alt text-pink-300"></i>
                    <span>Statistics</span>
                </a>
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-calculator text-pink-300"></i>
                    <span>Invoices</span>
                </a>
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-calendar5 text-pink-300"></i>
                    <span>Schedule</span>
                </a>
            </div>
        </div>
    </div>
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="index.html" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <span class="breadcrumb-item active">Dashboard</span>
            </div>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
        <div class="header-elements d-none">
            <div class="breadcrumb justify-content-center">
                <a href="#" class="breadcrumb-elements-item">
                    <i class="icon-comment-discussion mr-2"></i>
                    Support
                </a>
                <div class="breadcrumb-elements-item dropdown p-0">
                    <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-gear mr-2"></i>
                        Settings
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                        <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                        <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

UI/SMS.AdminUI/Views/Shared/Partials/_RemoveModalPartial.cshtml
@using (Ajax.BeginForm("Remove", "User", new AjaxOptions() { HttpMethod = "POST", OnBegin = "OnBegin", OnFailure = "OnFailure", OnSuccess = "OnSuccess" }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <div id="RemoveModalId" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Attention</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <input type="hidden" name="id" id="RemoveDataId" />
                    Are you sure to remove this data?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn bg-primary">Remove</button>
                </div>

            </div>
        </div>
    </div>
}

UI/SMS.AdminUI/Views/Shared/Partials/_SidebarPartial.cshtml
<!-- Main sidebar -->
<div class="sidebar sidebar-light sidebar-main sidebar-expand-md">
    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        <span class="font-weight-semibold">Navigation</span>
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->
    <!-- Sidebar content -->
    <div class="sidebar-content">
        @Html.Partial("Partials/SidebarPartials/_SidebarUserPartial")
        @Html.Partial("Partials/SidebarPartials/_SidebarMenuPartial")
    </div>
    <!-- /sidebar content -->

</div>
<!-- /main sidebar -->