UI/SMS.AdminUI/Controllers/UserPermissionController.cs
using AdminUI.ServiceFacades;
using BLL;
using DevExtreme.AspNet.Mvc;
using System.Web.Mvc;

namespace AdminUI.Controllers
{
    public class UserPermissionController : BaseController
    {
        private readonly UserPermissionServiceFacade _userPermissionServiceFacade;

        public UserPermissionController(UserPermissionServiceFacade userPermissionServiceFacade)
        {
            _userPermissionServiceFacade = userPermissionServiceFacade;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Data(DataSourceLoadOptions loadOptions)
        {
            var data = _userPermissionServiceFacade.GetAll();
            return GetTable<UserPermissionDTO>(data, loadOptions);
        }

        public ActionResult Form(long id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Remove()
        {
            return View();
        }
    }
}

UI/SMS.AdminUI/Views/Shared/Partials/SidebarPartials/_SidebarMenuPartial.cshtml
@using Common.Resources
<!-- Main navigation -->
<div class="card card-sidebar-mobile">
    <ul class="nav nav-sidebar" data-nav-type="accordion">
        <!-- Main -->
        <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
        <li class="nav-item nav-item-submenu">
            <a href="javascript:void(0)" class="nav-link"><i class="icon-copy"></i> <span>Security</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href="@Url.Action("Index","User")" class="nav-link active">@UI.Users</a></li>
                <li class="nav-item"><a href="@Url.Action("Index", "UserRole")" class="nav-link">Roles</a></li>
                <li class="nav-item"><a href="@Url.Action("Index", "UserPermission")" class="nav-link">Permissions</a></li>
            </ul>
        </li>
    </ul>
</div>
<!-- /main navigation -->

UI/SMS.AdminUI/Views/Shared/Partials/SidebarPartials/_SidebarUserPartial.cshtml
  <!-- User menu -->
<div class="sidebar-user-material">
    <div class="sidebar-user-material-body">
        <div class="card-body text-center">
            <a href="#">
                <img src="~/images/demo/users/face6.jpg" class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
            </a>
            <h6 class="mb-0 text-white text-shadow-dark">Victoria Baker</h6>
            <span class="font-size-sm text-white text-shadow-dark">Santa Ana, CA</span>
        </div>

        <div class="sidebar-user-material-footer">
            <a href="#user-nav" class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle" data-toggle="collapse"><span>My account</span></a>
        </div>
    </div>
    <div class="collapse" id="user-nav">
        <ul class="nav nav-sidebar">
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="icon-user-plus"></i>
                    <span>My profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="icon-coins"></i>
                    <span>My balance</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="icon-comment-discussion"></i>
                    <span>Messages</span>
                    <span class="badge bg-teal-400 badge-pill align-self-center ml-auto">58</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="icon-cog5"></i>
                    <span>Account settings</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="icon-switch2"></i>
                    <span>Logout</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- /user menu -->